---
apiVersion: "wso2.com/v1alpha2"
kind: "Integration"
metadata:
  name: "hello-world"
spec:
  image: "dushansachinda/mi-4.0.0.1:1.0.0-SNAPSHOT"
  deploySpec:
    minReplicas: 1
    requestCPU: "500m"
    reqMemory: "512Mi"
    cpuLimit: "2000m"
    memoryLimit: "2048Mi"
    livenessProbe:
      tcpSocket:
        port: 8290
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /healthz
        port: 9201
      initialDelaySeconds: 30
      periodSeconds: 10
  autoScale:
    enabled: "true"
    maxReplicas: 3
